### ISSUE TITLE
autoscaling doesn't work

### ISSUE THREAD

**Issue by maulikp-splunk** [splunk/splunk-connect-for-syslog#1289]
When specifying autoscaling configuration in values.yaml file as below:

```
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
```

Checking `kubectl describe hpa sc4s-splunk-connect-for-syslog` returns following error:

```
Type         Status  Reason          Message
  ----         ------  ------          -------
  AbleToScale  False   FailedGetScale  the HPA controller was unable to get the target's current scale: deployments/scale.apps "sc4s-splunk-connect-for-syslog" not found
```

[This](https://github.com/splunk/splunk-connect-for-syslog/blob/main/charts/splunk-connect-for-syslog/templates/hpa.yaml#L11) needs to be changed to StatefulSet, to fix this error.
