### ISSUE TITLE
Helm Chart Issue: metallb sharing key

### ISSUE THREAD

**Issue by ehlo550** [splunk/splunk-connect-for-syslog#1541]
Hi,

Thanks for all the work! 
I just noticed the following issue: 
When using
``` helm template --dry-run --debug ./splunk-connect-for-syslog --generate-name ``` 

I get 
```
Error: template: splunk-connect-for-syslog/templates/service.yaml:86:25: executing "splunk-connect-for-syslog/templates/service.yaml" at <.Values.usemetallb>: nil pointer evaluating interface {}.usemetallb
helm.go:84: [debug] template: splunk-connect-for-syslog/templates/service.yaml:86:25: executing "splunk-connect-for-syslog/templates/service.yaml" at <.Values.usemetallb>: nil pointer evaluating interface {}.usemetallb
```

The root cause is in the service.yaml
For example for the tcp service there is:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-connect-for-syslog.fullname" . }}-tcp
  annotations:
  {{- if (default .Values.usemetallb true) }}
    metallb.universe.tf/allow-shared-ip: {{ .Values.metallbsharingkey | default "splunk-connect" | quote }}
  {{- end }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "splunk-connect-for-syslog.labels" . | nindent 4 }}
```

This should probably be:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-connect-for-syslog.fullname" . }}-tcp
  annotations:
  {{- if or .Values.usemetallb (not (hasKey .Values "usemetallb")) }}
    metallb.universe.tf/allow-shared-ip: {{ .Values.metallbsharingkey | default "splunk-connect" | quote }}
  {{- end }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "splunk-connect-for-syslog.labels" . | nindent 4 }}
```
Have a look at the following helm issue regarding [default functions](https://github.com/helm/helm/issues/3308)

What is odd is that the udp service is defined differently. 
```
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-connect-for-syslog.fullname" . }}-udp
  {{- with .Values.service.annotations }}
  annotations:
  {{- if (default .Values.usemetallb true) }}
    metallb.universe.tf/allow-shared-ip: {{ .Values.metallbsharingkey | default "splunk-connect" | quote }}
  {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "splunk-connect-for-syslog.labels" . | nindent 4 }}
```

When fixing this with the above, we get a service.yaml that has two metallb sharing keys, as there is also a sharing key defined via .Values.service.annotations. 
```
# Source: splunk-connect-for-syslog/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-splunk-connect-for-syslog-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "splunk-connect"
    metallb.universe.tf/allow-shared-ip: splunk-edge
  labels:
    helm.sh/chart: splunk-connect-for-syslog-2.12.1
    app.kubernetes.io/name: splunk-connect-for-syslog
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.12.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "input"
    app.kubernetes.io/part-of: "Splunk"
```

I am currently not sure which way is the intended way and therefore won't open a PR but can of course open one if you can tell me if 

a.) .Values.service.annotations 
or
b.) .Values.usemetallb 

is the way to go (Although (b) would probably make more sense to me) 

Regards
