### ISSUE TITLE
secret.yaml" at <b64enc>: invalid value; expected string

### ISSUE THREAD

**Issue by mgrune9978** [splunk/splunk-connect-for-syslog#1868]
I'm seeing this issue where I try to deploy the sc4s chart using a pipeline.  I thought it's probably something in my pipeline syntax, however I get this same error when trying to deploy the chart from the commandline.  aka

```helm install --values values.yaml --namespace test test-sc4s splunk-connect-for-syslog/splunk-connect-for-syslog```

The values I'm using are super simple for this test:
```
replicaCount: 1

splunk:
  hec_url: "MYURL"
  hec_token: "MyTOKEN"
  hec_verify_tls: "yes"
```

I just get this no matter what I do.  Even if I don't set any values I get this same error.
```
Error: INSTALLATION FAILED: template: splunk-connect-for-syslog/templates/secret.yaml:6:36: executing "splunk-connect-for-syslog/templates/secret.yaml" at <b64enc>: invalid value; expected string
```

**Comment by rjha-splunk** [comment]
@mateuszpierzchala-splunk Can you please check this ?

**Comment by ehlo550** [comment]
as a workaround delete the secrets.yaml from templates directory

or
change your values.yaml like this:

from:
```
splunk:
  hec_url: "https://whatthehec.wtf.com/services/collector/event"
  hec_token: "1234"
  hec_verify_tls: "yes"
```
to
```
hec_token: "1234"
splunk:
  hec_url: "https://whatthehec.wtf.com/services/collector/event"
  hec_verify_tls: "yes"
```
