### ISSUE TITLE
compliance_meta_by_source overrides don't work in k8s - entrypoint not copying files

### ISSUE THREAD

**Issue by luedderd** [splunk/splunk-connect-for-syslog#1963]
We are running 2.43.2 in k8s via a helm chart and I am attempting to override the index for events matching a hostname filter.

The relevant section from the `values.yaml` file:

```
sc4s:
  context_files:
    compliance_meta_by_source.conf: |-
      filter f_cisco_router {
          host("rtr*" type(glob))
      };
      filter f_cisco_switch {
          host("sw*" type(glob))
      };
    compliance_meta_by_source.csv: |-
      f_cisco_router,.splunk.index,"router"
      f_cisco_switch,.splunk.index,"switch"
    splunk_metadata.csv: |-
      cisco_ftd,index,firewall
      cisco_asa,index,firewall
      cisco_ios,index,network
      fallback,index,clogs
```

We have validated that the ftd/asa and other ios events land in the proper index, however any devices with hostnames matching the glob are not going into the appropriate indexes.

After exec'ing into one of the pods, I validated the context files as configured in `values.yaml` exist in the `/etc/syslog-ng/conf.d/configmap/context/` directory, but the files in `/etc/syslog-ng/conf.d/local/context/` are still blank.

Searching the issues here, I discovered #1576 and #1639, both closed and apparently unresolved. It seems the docs are outdated as to how this is supposed to be implemented. I am not sure I understand the new process referenced in the closing comment of #1639:

> Other configmaps files are deprecated in v2 , the code needs to be corrected to remove the empty files and document will be revised , now the way to implement this feature is by using a .conf file in local/config/app_parsers/<filename>.conf

What is the proper way to implement this via the k8s-deployed values.yaml configuration?

**Comment by rjha-splunk** [comment]
We do see some gap in implementing the app_parsers in the configuration for k8s , i will keep this bug open and we will fix it in coming sprints , for now it can be implemented with Kustomize ( thank you @ehlo550 for suggestion) 

Example how it can be implemented :

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sc4s-test-app-parser
data:
  app-workaround-cisco_asa.conf: |+
    #/opt/sc4s/local/config/filters/app-postfilter-drop_metadata.conf
    block parser app-postfilter-cisco_asa_metadata() {
      channel {
        rewrite {
          unset(value('fields.sc4s_recv_time'));
        };
      };
    };

    application app-postfilter-cisco_asa_metadata[sc4s-postfilter] {
      filter {
        'cisco' eq "${fields.sc4s_vendor}"
        and 'asa' eq "${fields.sc4s_product}"
      };
        parser { app-postfilter-cisco_asa_metadata(); };
    };
```

Here use Kustomize and patch the statefulness:

```
---
apiVersion: kustomize.config.k8s.io/beta
kind: Kustomization
namespace: sc4s

resources:
  - ../../base
  - configmap-context.yaml
  - configmap-app-parser.yaml

patchesJson:
  - target:
      kind: StatefulSet
      name: sc4s-splunk-connect-for-syslog
    path: patch-configmap-app-parser.yaml
```
to include the path for configmap , following patch-configmap-app-parser.yaml file can be used 

```
---
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: app-parser
    configMap:
      name: sc4s-test-app-parser

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: app-parser
    mountPath: /etc/syslog-ng/conf.d/local/config/app_parsers
```

We will fix the include of app parser in main config (k8s) in 2nd week of Jan after testing it.
