### ISSUE TITLE
PFsense logs come in with wrong source / sourcetype

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-connect-for-syslog#978]
PFsense Firewall logs come in as sourcetype=nix:syslog source=program:kernel.

![image](https://user-images.githubusercontent.com/6953914/107859131-6dbe1e00-6e05-11eb-8198-b9f3aa742364.png)

**Comment by mbonsack** [comment]
These are likely because the parser determined these were generic linux system (OS) messages from the underlying platform which are best represented by `nix:syslog`.  In this case, though, it does appear as if these could be classified as relevant FW events, though it appears to just be interface statistics.

Can you post an "on the wire" raw message (with the <PRI> string intact) of this event or a similar one?  This is best obtained with `tcpdump`.  Also, can you post raw messages of any events that _are_ correct?  Thanks.

**Comment by satellite-no** [comment]
Hey, 
Thanks for the quick response. Below is some of the one the wire data as of right now there have been no events classified correctly.  I also tried to set the IP in vendor_product_by_source.conf, this fails to work as well.  

`filter f_pfsense {
    host("pfsense-*" type(glob))
    or netmask(10.1.0.4/32)
};`

`14:01:37.894086 IP (tos 0x0, ttl 63, id 8834, offset 0, flags [none], proto UDP (17), length 160)
    10.1.0.4.syslog > sc4s.mybeda.com.syslog: SYSLOG, length: 132
	Facility local0 (16), Severity info (6)
	Msg: Feb 13 14:01:37 filterlog: 5,,,1000000103,em0,match,block,in,4,0x0,,64,33796,0,DF,17,udp,63,10.1.0.86,10.1.0.255,37341,15600,43
14:01:38.894355 IP (tos 0x0, ttl 63, id 43068, offset 0, flags [none], proto UDP (17), length 169)
    10.1.0.4.syslog > sc4s.mybeda.com.syslog: SYSLOG, length: 141
	Facility local0 (16), Severity info (6)
	Msg: Feb 13 14:01:38 filterlog: 5,,,1000000103,em0,match,block,in,4,0x0,,255,34844,0,none,17,udp,199,10.1.0.92,255.255.255.255,49157,6666,179`

**Comment by mbonsack** [comment]
Unfortunately, that's not raw.  Use a different argument to `tcpdump` that doesn't decode the syslog header.  I need the `<PRI>` string intact (in other words, I need to "play back" this event to my sc4s instance to duplicate your issue).  I can figure out what that string will be given your dump above, but I'd rather see it as it appears "on the wire" and not decoded.

**Comment by mbonsack** [comment]
For the filter you set above, did you reference it in `vendor_product_by_source.csv`?

**Comment by mbonsack** [comment]
And is this `pfsense` or Ubiquiti `USG`?  Maybe you built the filter for the wrong vendor/product?

**Comment by mbonsack** [comment]
I did manage to reproduce your event above into sourcetype `nix:syslog`.  I really need to know now, at this point, what vendor/device this is.  Confused between pfsense or Ubiquiti.

**Comment by satellite-no** [comment]
Try the attached pcap (remove .txt) for the raw on the wire Syslog messages.

The above filter is the default filter I just added the address to match the source.  The default `vendor_product_by_source.csv` already has a line `f_pfsense,sc4s_vendor_product,"pfsense"` that matches this filter does more need to be referenced than this?  The docs say to create an "ip filter" for this sourcetype but are real light on details.

https://splunk-connect-for-syslog.readthedocs.io/en/master/sources/Pfsense/

[dump.pcap.txt](https://github.com/splunk/splunk-connect-for-syslog/files/5976318/dump.pcap.txt)

This is my first venture into trying to make use of this SC4S and trying to really get a deep understanding of it so I can start implementing it / teaching it to my team.

**Comment by satellite-no** [comment]
This is pfsense, apologies for the confusion I pasted the wrong event in the original message but have updated it to reflect the correct events.  I do have issues with USG but I'm focusing on one issue at a time.

**Comment by satellite-no** [comment]
This may be entirely on me and my configuration.  I'm trying to setup without the separate port and use the IP filter as described in the doc.  

"Configure a dedicated SC4S port OR configure IP filter"

Is setting up the IP filter done via the vendor_product.conf using syslogng filter correct?

**Comment by mbonsack** [comment]
So -- please post your `vendor_product_by_source.conf` file again to see what the actual filter looks like.  Also, if you could look at the indexed field `sc4s_fromhostip` in your event to see if you really have the IP correct, that would be helpful to diagnose why your filter didn't fire.

**Comment by satellite-no** [comment]
Ya, I don't get why the filter isn't triggering either. 

Also, another oddity is it's assigning the host of 172.x.0.1 which I have no idea where that comes from I have no 172.x.x.x IPs on my network.

vendor_product_by_source.conf:
filter f_pfsense {
    host("pfsense-*" type(glob))
    or host("10.1.0.4")
    or network(10.1.0.4/32)
};

vendor_product_by_source.csv:
f_pfsense,sc4s_vendor_product,"pfsense"

`tcpdump -X -i ens18 src 10.1.0.4 -v`
pfsense-beda.mybeda.com.syslog > sc4s.mybeda.com.syslog: SYSLOG, length: 141
	Facility local0 (16), Severity info (6)
    <134>Feb.13.20:15:59.filterlog:.5,,,1000000103,em0,match,block,in,4,0x0,,255,43089,0,none,17,udp,199,10.1.0.92,255.255.255.255,49157,6666,179


Side note, when I set a separate listening port it works as expected.

**Comment by satellite-no** [comment]
Follow up, 
I missed explaining `sc4s_fromhostip` more thoroughly below image shows that field is the same as the `host` field.  However, I have no idea where SC4S is coming up with that IP my network is ALL 10.x.x.x addresses I have zero 172.x.x.x addresses and if i start-stop the container it will iterate up one number in the second octet.  The second image shows a tcpdump that was running for 5min with that IP as a filter with zero results, I'm really baffled at this one. 

![image](https://user-images.githubusercontent.com/6953914/107866753-ecd14780-6e41-11eb-8ebe-5f9d422f0979.png)

![image](https://user-images.githubusercontent.com/6953914/107866808-8dc00280-6e42-11eb-921d-3fd8f7b7b8d9.png)

**Comment by mbonsack** [comment]
Well, for now use `172.18.0.1` in your filter, because that's what syslog-ng under the hood thinks is the originating IP.  It will likely work, and at that point we can figure out what router (or load balancer) is munging your source IP :-)

**Comment by mbonsack** [comment]
Do an `ifconfig` to see if you have any virtual NICs with that IP range too.

**Comment by mbonsack** [comment]
Also post your unit file (if using systemctl); want to make sure you're using host networking with podman/docker and not virtual container networking (like we used to do in the older versions).

**Comment by satellite-no** [comment]
So looks like were getting closer... it does appear to be something with the virtual network.

```
17: br-bdca27292e73: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 02:42:69:1b:cb:4b brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.1/16 brd 172.21.255.255 scope global br-bdca27292e73
       valid_lft forever preferred_lft forever

18: br-fa9104817865: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 02:42:c9:66:ac:5c brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.1/16 brd 172.22.255.255 scope global br-fa9104817865
       valid_lft forever preferred_lft forever

99: br-4bc3adfe005c: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:bb:78:6e:af brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-4bc3adfe005c
       valid_lft forever preferred_lft forever
    inet6 fe80::42:bbff:fe78:6eaf/64 scope link
       valid_lft forever preferred_lft forever
```

I am using the docker-compose from the [mac](https://splunk-connect-for-syslog.readthedocs.io/en/master/gettingstarted/docker-compose-MacOS/) setup. 

```
---
version: "3.7"
services:
  sc4s:
    image: docker.io/splunk/scs:latest
    ports:
       - target: 514
         published: 514
         protocol: tcp
       - target: 514
         published: 514
         protocol: udp
       #- target: 601
       #  published: 601
       #  protocol: udp
       #- target: 6514
       #  published: 6514
       #  protocol: tcp
    env_file:
      - env_file
    volumes:
      - /opt/sc4s/local:/etc/syslog-ng/conf.d/local:z
      - splunk-sc4s-var:/var/lib/syslog-ng
# Uncomment the following line if local disk archiving is desired
      - /opt/sc4s/archive:/var/lib/syslog-ng/archive:z
# Uncomment the following line if custom TLS certs are provided
#     - /opt/sc4s/tls:/etc/syslog-ng/tls:z

volumes:
  splunk-sc4s-var:
```

**Comment by satellite-no** [comment]
Updated docker-compose to the below and use the `host` network and it appears to be working as expected.  I guess the docker network is nat'ing the address for pfsense but not the unifi stuff (scratches head)?  Everything was set to use default 514. 

```
---
version: "3.7"
services:
  #newtork_mode: host
  sc4s:
    network_mode: host
    image: docker.io/splunk/scs:latest
    #ports:  
       #- target: 514
       #  published: 514
       #  protocol: tcp
       #- target: 514
       #  published: 514
       #  protocol: udp
       #- target: 601
       #  published: 601
       #  protocol: tcp
       #- target: 6514
       #  published: 6514
       #  protocol: tcp
    env_file:
      - env_file
    volumes:
      - /opt/sc4s/local:/etc/syslog-ng/conf.d/local:z
      - splunk-sc4s-var:/var/lib/syslog-ng
# Uncomment the following line if local disk archiving is desired
      - /opt/sc4s/archive:/var/lib/syslog-ng/archive:z
# Uncomment the following line if custom TLS certs are provided
#     - /opt/sc4s/tls:/etc/syslog-ng/tls:z

volumes:
  splunk-sc4s-var:
```
